export const siteContent = {
  company: {
    name: 'PANESSO MERCADO ABOGADOS',
    tagline: 'Asesoría legal integral para transformar su empresa',
  },
  navigation: [
    { label: 'Inicio', href: '/' },
    { label: 'Servicios', href: '/servicios' },
    { label: 'Nosotros', href: '/#socios' },
    { label: 'Contacto', href: '/#contacto' },
  ],
  hero: {
    headings: [
      'Transformamos momentos difíciles en soluciones legales que te permiten avanzar.',
      'Protegemos lo que más importa.',
      'Convertimos desafíos legales en soluciones estratégicas.',
      'La confianza se construye con resultados.',
      'Cada decisión merece el respaldo correcto.',
      'Su tranquilidad comienza con una estrategia legal sólida.',
    ],
    subtitle: 'Brindamos asesoría y representación jurídica integral a personas, familias y empresas, con un enfoque estratégico, humano y personalizado. Acompañamos cada caso con excelencia, compromiso y rigor legal para ofrecer soluciones claras, proteger sus intereses y generar confianza en cada decisión.',
    cta: 'Agenda tu consulta',
  },
  partners: [
    {
      id: 1,
      name: 'Hernán Panesso',
      title: 'Fundador',
      specialties: 'Derecho de la Competencia, Privacidad de Datos, Telecomunicaciones, Regulación Económica',
      image: '/images/partners/hernan.png',
      modalImage: '/images/practice-areas/socios.png',
      fullInfo: {
        profile: 'Su práctica se concentra en derecho de la competencia, privacidad y protección de datos, derecho del consumo, derecho administrativo sancionatorio, litigio administrativo, telecomunicaciones, regulación económica y metrología legal. Asesora a empresas nacionales y extranjeras en sus procedimientos ante la Superintendencia de Industria y Comercio (SIC) y en asuntos de regulación económica. Ha dirigido y participado en numerosas operaciones de concentración empresarial, nacionales y transfronterizas, y en investigaciones por prácticas restrictivas de la competencia.',
        practiceAreas: [
          'Derecho de la Competencia',
          'Privacidad y Protección de Datos',
          'Derecho del Consumo',
          'Derecho Administrativo Sancionatorio',
          'Telecomunicaciones y Regulación Económica',
          'Metrología Legal y Reglamentos Técnicos',
        ],
        experience: [
          'Más de 50 operaciones de control de integraciones empresariales ante la SIC',
          'Investigaciones por prácticas restrictivas de la competencia y carteles',
          'Protección al consumidor: campañas de retiro de productos, seguridad e idoneidad de producto',
          'Protección de datos personales: programas de cumplimiento, gestión de incidentes',
          'Asesoría regulatoria en telecomunicaciones y gestión del espectro radioeléctrico',
        ],
        education: [
          'Universidad de Oxford — Magíster en Derecho (Magister Juris)',
          'Universidad del Rosario — Especialización en Derecho Económico y de los Mercados',
          'Universidad del Rosario — Abogado',
          'Profesor de derecho de la competencia y regulación económica en Universidad Javeriana, CESA y Universidad de la Sabana',
        ],
      },
    },
    {
      id: 2,
      name: 'María Esther Panesso Mercado',
      title: 'Socia Fundadora – Directora Jurídica',
      specialties: 'Derecho de Familia, Derecho de Sucesiones, Derecho Civil, Planeación Patrimonial',
      image: '/images/partners/esther.png',
      modalImage: '/images/practice-areas/imagen-familia.png',
      fullInfo: {
        profile: 'Abogada y Administradora de Negocios Internacionales de la Universidad de La Sabana, con Executive MBA del IE Business School de Madrid (España). Desde hace más de quince (15) años dirige una firma de abogados especializada en Derecho de Familia, Derecho de Sucesiones, Derecho Civil y Planeación Patrimonial, liderando la representación y asesoría de personas, familias y empresas en asuntos de alta complejidad jurídica y patrimonial.\n\nSu ejercicio profesional se ha distinguido por la dirección estratégica de procesos judiciales y extrajudiciales relacionados con conflictos familiares, procesos sucesorales, liquidaciones de sociedades conyugales y patrimoniales, protección del patrimonio familiar, estructuración de acuerdos, negociación y resolución integral de controversias. Su formación simultánea en Derecho y Administración de Negocios Internacionales le permite integrar el análisis jurídico con una visión empresarial, financiera y estratégica, considerando las implicaciones económicas, patrimoniales y corporativas de cada decisión.\n\nComo Directora Jurídica, lidera un equipo interdisciplinario conformado por abogados especializados en Derecho de Familia, Derecho Civil, Derecho Corporativo y Societario, Derecho Contractual, Derecho Comercial, Derecho Laboral, Derecho Inmobiliario, Compliance y Litigios, garantizando un servicio integral bajo los más altos estándares de calidad, confidencialidad y responsabilidad profesional.',
        practiceAreas: [
          'Derecho de Familia',
          'Derecho de Sucesiones',
          'Derecho Civil',
          'Planeación y Protección Patrimonial',
          'Negociación y Resolución de Controversias',
        ],
        experience: [
          'Procesos de divorcio y cesación de efectos civiles del matrimonio',
          'Liquidación de sociedades conyugales y patrimoniales',
          'Procesos sucesorales judiciales y notariales',
          'Planeación, organización y protección del patrimonio familiar',
          'Elaboración y negociación de acuerdos de familia',
          'Representación judicial en procesos civiles y de familia',
          'Litigios patrimoniales',
          'Asesoría preventiva para mitigación de riesgos jurídicos',
          'Elaboración y negociación de contratos civiles y comerciales',
          'Representación judicial y extrajudicial de personas naturales y jurídicas',
        ],
        education: [
          'IE Business School (Madrid, España) — Executive MBA',
          'Universidad de La Sabana — Abogada',
          'Universidad de La Sabana — Administradora de Negocios Internacionales',
        ],
        recognition: [
          'Condecoración del Senado de la República de Colombia, en reconocimiento a su destacada trayectoria profesional, liderazgo jurídico y contribución al fortalecimiento de la justicia y la defensa de los derechos de las mujeres',
          'Dos condecoraciones del Concejo de Bogotá, concedidas en reconocimiento a su excelencia profesional, liderazgo social, servicio a la ciudad y permanente compromiso con la promoción de los derechos de las mujeres',
          'Condecoración del Parlamento Andino, otorgada en reconocimiento a su liderazgo, compromiso con el fortalecimiento institucional y aporte al desarrollo social de la región',
          'Condecoración de la Procuraduría General de la Nación, conferida en reconocimiento a su compromiso con la defensa de los derechos de las mujeres, la promoción de la equidad y el fortalecimiento de la cultura de legalidad',
        ],
        socialCommitment: 'Desarrolla una permanente labor social orientada a la promoción, protección y defensa de los derechos de las mujeres, brindando acompañamiento jurídico en asuntos relacionados con violencia intrafamiliar, protección patrimonial, conflictos familiares y acceso efectivo a la justicia. Su trabajo ha estado dirigido a fortalecer la autonomía jurídica y económica de las mujeres, promoviendo la igualdad de oportunidades, la protección de la familia y el respeto por la dignidad humana como pilares fundamentales del Estado Social de Derecho.',
        philosophy: 'El ejercicio del Derecho exige conocimiento, independencia, criterio y profundo sentido humano. Cada asunto representa la confianza depositada por una persona o una familia en momentos determinantes de su vida. Por ello, la práctica jurídica debe orientarse no solo a resolver conflictos, sino a proteger el patrimonio, preservar la dignidad de las personas y construir soluciones que generen seguridad jurídica y tranquilidad para las generaciones presentes y futuras.',
      },
    },
  ],
  practiceAreas: [
    {
      id: 1,
      title: 'Derecho de la Competencia',
      description: 'Asesoría especializada en asuntos de competencia económica, prácticas restrictivas, concentraciones empresariales y regulación de mercados.',
      icon: '📊',
      image: '',
      services: [
        'Operaciones de concentración empresarial',
        'Investigaciones por prácticas restrictivas de la competencia',
        'Carteles y acuerdos entre competidores',
        'Abuso de posición dominante',
        'Defensa ante autoridades de competencia',
        'Asesoría en regulación de mercados',
        'Litigios de competencia',
        'Cumplimiento normativo en competencia',
      ],
    },
    {
      id: 2,
      title: 'Privacidad y Protección de Datos',
      description: 'Compliance en privacidad de datos personales, HABEAS DATA, seguridad de información y protección de derechos digitales.',
      icon: '🔒',
      image: '',
      services: [
        'Programas de cumplimiento en privacidad',
        'Gestión de incidentes de seguridad',
        'Políticas de protección de datos',
        'Derechos HABEAS DATA',
        'Evaluaciones de impacto de privacidad',
        'Asesoría a responsables y encargados de datos',
        'Cumplimiento normativo en privacidad',
        'Litigio en asuntos de datos personales',
      ],
    },
    {
      id: 3,
      title: 'Derecho del Consumo',
      description: 'Asesoría en protección al consumidor, publicidad comercial, seguridad de productos y relaciones de consumo.',
      icon: '🛍️',
      image: '',
      services: [
        'Defensa de derechos del consumidor',
        'Campañas de retiro de productos',
        'Seguridad e idoneidad de productos',
        'Publicidad comercial y prácticas desleales',
        'Reclamaciones ante autoridades de consumo',
        'Litigios de consumo',
        'Cumplimiento de normativa de consumidor',
        'Asesoría a proveedores de bienes y servicios',
      ],
    },
    {
      id: 4,
      title: 'Derecho Administrativo Sancionatorio',
      description: 'Representación en procedimientos sancionatorios, defensa ante autoridades administrativas y recursos contra actos administrativos.',
      icon: '⚖️',
      image: '',
      services: [
        'Defensa en procedimientos sancionatorios',
        'Investigaciones administrativas',
        'Recursos contra actos administrativos',
        'Nulidad de actos administrativos',
        'Reparación patrimonial',
        'Asesoría a servidores públicos',
        'Litigio administrativo',
        'Cumplimiento normativo administrativo',
      ],
    },
    {
      id: 5,
      title: 'Telecomunicaciones y Regulación Económica',
      description: 'Asesoría especializada en regulación de telecomunicaciones, gestión del espectro radioeléctrico y asuntos de regulación económica sectorial.',
      icon: '📡',
      image: '',
      services: [
        'Gestión del espectro radioeléctrico',
        'Autorizaciones y permisos en telecomunicaciones',
        'Acceso a infraestructura de telecomunicaciones',
        'Cumplimiento de obligaciones regulatorias',
        'Regulación de servicios públicos',
        'Asesoría en sectores regulados',
        'Procedimientos ante autoridades regulatorias',
        'Litigio regulatorio',
      ],
    },
    {
      id: 6,
      title: 'Metrología Legal y Reglamentos Técnicos',
      description: 'Asesoría en metrología legal, reglamentos técnicos, normalización y certificación de productos.',
      icon: '📏',
      image: '',
      services: [
        'Cumplimiento de reglamentos técnicos',
        'Certificación de productos',
        'Marcado y etiquetado',
        'Organismos de inspección y certificación',
        'Procedimientos ante autoridades metronómicas',
        'Defensa ante sanciones en metrología',
        'Asesoría en normalización técnica',
        'Importación y comercialización de productos',
      ],
    },
    {
      id: 7,
      title: 'Derecho de Familia',
      description: 'Asesoría integral en temas de familia, separaciones, custodia de menores, divorcio y acuerdos patrimoniales.',
      icon: '👨‍👩‍👧‍👦',
      image: '/images/practice-areas/familia.png',
      services: [
        'Divorcio de mutuo acuerdo',
        'Divorcio contencioso',
        'Liquidación de sociedad conyugal',
        'Liquidación de sociedad patrimonial',
        'Cuota alimentaria',
        'Custodia y regulación de visitas',
        'Procesos de filiación e impugnación de paternidad',
        'Sucesiones',
        'Testamentos',
        'Partición y adjudicación de bienes',
        'Procesos de apoyos judiciales',
        'Protección patrimonial familiar',
      ],
    },
    {
      id: 8,
      title: 'Derecho Corporativo y Societario',
      description: 'Constitución de sociedades, gobierno corporativo, fusiones, adquisiciones y reestructuraciones empresariales.',
      icon: '🏢',
      image: '/images/practice-areas/socios.png',
      services: [
        'Constitución de sociedades',
        'Reformas estatutarias',
        'Acuerdos de accionistas',
        'Secretaría societaria',
        'Actas y libros corporativos',
        'Fusiones y reorganizaciones empresariales',
        'Capitalizaciones',
        'Gobierno corporativo',
        'Trámites ante Cámaras de Comercio',
        'Representación legal corporativa',
      ],
    },
    {
      id: 9,
      title: 'Derecho Contractual y Comercial',
      description: 'Redacción y negociación de contratos, asesoría comercial y relaciones contractuales.',
      icon: '📋',
      image: '/images/practice-areas/imagen-familia.png',
      services: [
        'Elaboración de contratos',
        'Revisión y negociación contractual',
        'Contratos comerciales',
        'Contratos civiles',
        'Contratos de distribución',
        'Contratos de suministro',
        'Contratos de prestación de servicios',
        'Acuerdos de confidencialidad',
        'Estructuración jurídica de negocios',
      ],
    },
    {
      id: 10,
      title: 'Litigios y Solución de Controversias',
      description: 'Representación en procesos judiciales, arbitraje y mediación para resolución de conflictos.',
      icon: '⚖️',
      image: '/images/practice-areas/negociacion.png',
      services: [
        'Procesos ejecutivos',
        'Procesos declarativos',
        'Responsabilidad civil contractual y extracontractual',
        'Cobro de cartera',
        'Medidas cautelares',
        'Recursos y apelaciones',
        'Conciliaciones',
        'Negociación y solución de conflictos',
      ],
    },
    {
      id: 11,
      title: 'Derecho Laboral',
      description: 'Relaciones laborales, negociación colectiva, resolución de conflictos y cumplimiento normativo.',
      icon: '👥',
      image: '/images/practice-areas/familia.png',
      services: [
        'Asesoría a empleadores',
        'Contratación laboral',
        'Reglamentos internos',
        'Procesos disciplinarios',
        'Terminación de contratos',
        'Liquidaciones laborales',
        'Defensa judicial laboral',
        'Atención de requerimientos del Ministerio del Trabajo',
      ],
    },
    {
      id: 12,
      title: 'Compliance y Gobierno Corporativo',
      description: 'Programas de compliance, gobierno corporativo, cumplimiento normativo y asuntos regulatorios.',
      icon: '✓',
      image: '/images/practice-areas/socios.png',
      services: [
        'Implementación de SAGRILAFT',
        'Implementación de PTEE',
        'Oficial de Cumplimiento externo',
        'Debida diligencia',
        'Auditorías de cumplimiento',
        'Protección de datos personales',
        'Gestión de riesgos corporativos',
        'Capacitación empresarial',
      ],
    },
    {
      id: 13,
      title: 'Derecho Inmobiliario',
      description: 'Transacciones inmobiliarias, propiedad horizontal, leasing y asuntos de bienes raíces.',
      icon: '🏠',
      image: '/images/practice-areas/imagen-familia.png',
      services: [
        'Compraventa de inmuebles',
        'Estudios de títulos',
        'Promesas de compraventa',
        'Arrendamientos',
        'Propiedad horizontal',
        'Hipotecas',
        'Saneamiento de títulos',
        'Restitución de inmuebles',
      ],
    },
    {
      id: 14,
      title: 'Planeación Patrimonial y Sucesoral',
      description: 'Planificación patrimonial, testamentos, herencias y estrategias de transmisión de bienes.',
      icon: '💰',
      image: '/images/practice-areas/negociacion.png',
      services: [
        'Planeación sucesoral',
        'Protocolos de familia',
        'Fideicomisos',
        'Patrimonios autónomos',
        'Protección patrimonial',
        'Estructuración de patrimonio familiar y empresarial',
      ],
    },
  ],
  testimonials: [
    {
      quote: 'Panesso Mercado proporciona asesoría de clase mundial con profundo conocimiento del mercado local.',
      source: 'Legal 500',
      author: 'Empresa Multinacional',
    },
    {
      quote: 'El equipo demuestra excelencia en resolución de casos complejos de derecho corporativo.',
      source: 'Chambers & Partners',
      author: 'Corporación Financiera',
    },
    {
      quote: 'Destacan por su innovación y enfoque tecnológico en la práctica legal.',
      source: 'Legal 500',
      author: 'Startup de Tecnología',
    },
    {
      quote: 'Recomendamos especialmente su práctica de litigio estratégico.',
      source: 'Chambers & Partners',
      author: 'Grupo Industrial',
    },
    {
      quote: 'Su conocimiento en materia tributaria es inmejorable en el mercado.',
      source: 'Legal 500',
      author: 'Sociedad de Capital',
    },
    {
      quote: 'Excelente manejo de transacciones internacionales y cross-border.',
      source: 'Chambers & Partners',
      author: 'Banco de Inversión',
    },
    {
      quote: 'Profesionalismo y atención personalizada en cada proyecto.',
      source: 'Legal 500',
      author: 'Empresa de Servicios',
    },
    {
      quote: 'Los mejores en resolución de conflictos laborales y relaciones industriales.',
      source: 'Chambers & Partners',
      author: 'Grupo Empresarial',
    },
    {
      quote: 'Confiamos en ellos para nuestros asuntos más críticos y estratégicos.',
      source: 'Legal 500',
      author: 'Holding Corporativo',
    },
  ],
  cta: {
    heading: '¿Tiene un desafío legal o regulatorio?',
    description: 'Permítanos ayudarle a navegar la complejidad legal y alcanzar sus objetivos empresariales con estrategia y excelencia.',
    buttonText: 'Contáctenos',
  },
  footer: {
    logo: 'PANESSO MERCADO ABOGADOS',
    tagline: 'Transformando desafíos legales en oportunidades',
    sections: {
      firma: {
        title: 'Navegación',
        links: [
          { label: 'Inicio', href: '/' },
          { label: 'Servicios', href: '/servicios' },
          { label: 'Nosotros', href: '/#socios' },
          { label: 'Contacto', href: '/#contacto' },
        ],
      },
      contacto: {
        title: 'Contacto',
        address: 'Calle 95 # 15-33, Oficina 204',
        city: 'Bogotá D.C., Colombia',
        phone: '+57 (1) 3133900829',
        email: 'contacto@panessomercado.com',
      },
    },
    social: [],
    copyright: '© 2024 Panesso Mercado Abogados. Todos los derechos reservados.',
  },
  resources: {
    articles: [
      'Tendencias en Derecho Corporativo 2024',
      'Guía de Cumplimiento Tributario',
      'Transformación Digital en el Sector Legal',
    ],
    webinars: [
      'Regulación Ambiental Empresarial',
      'M&A Strategy and Execution',
      'Labor Law Updates',
    ],
  },
};
